### ISSUE TITLE
Can't compute-type and compute-nf

### ISSUE THREAD

**Issue by by-cloud** [aya-prover/aya-vscode#12]
After press `ctrl+l ctrl+p` or `ctrl+l ctrl+n`, we have error report in debug console:

```
Error: Invalid arguments
	at new l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:21239)
	at new l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:17220)
	at applyComputedTerm (/Users/claude/Downloads/projects/aya/aya-vscode/out/compute-term.js:21:24)
	at /Users/claude/Downloads/projects/aya/aya-vscode/out/features.js:24:152
```

I think the `result` passed to `applyComputedTerm(...)` is not in the right format, then I have no clue.

**Comment by imkiva** [comment]
It seems we didn't fix this problem in some cases.
